use bancho_protocol_macros::{BinaryDeserialize, BinarySerialize, ByteSized};
#[repr(u8)]
#[derive(Debug, BinarySerialize, BinaryDeserialize, ByteSized)]
#[crate_root(crate)]
pub enum Country {
    Unknown, // XX
    Oceania, // OC
    Europe, // EU
    Andorra, // AD
    UAE, // AE
    Afghanistan, // AF
    Antigua, // AG
    Anguilla, // AI
    Albania, // AL
    Armenia, // AM
    Antilles, // AN
    Angola, // AO
    Antarctica, // AQ
    Argentina, // AR
    AmericanSamoa, // AS
    Austria, // AT
    Australia, // AU
    Aruba, // AW
    Azerbaijan, // AZ
    Bosnia, // BA
    Barbados, // BB
    Bangladesh, // BD
    Belgium, // BE
    BurkinaFaso, // BF
    Bulgaria, // BG
    Bahrain, // BH
    Burundi, // BI
    Benin, // BJ
    Bermuda, // BM
    BruneiDarussalam, // BN
    Bolivia, // BO
    Brazil, // BR
    Bahamas, // BS
    Bhutan, // BT
    BouvetIsland, // BV
    Botswana, // BW
    Belarus, // BY
    Belize, // BZ
    Canada, // CA
    CocosIslands, // CC
    DRCongo, // CD
    CentralAfricanRepublic, // CF
    Congo, // CG
    Switzerland, // CH
    CoteDIvoire, // CI
    CookIslands, // CK
    Chile, // CL
    Cameroon, // CM
    China, // CN
    Colombia, // CO
    CostaRica, // CR
    Cuba, // CU
    CapeVerde, // CV
    ChristmasIsland, // CX
    Cyprus, // CY
    CzechRepublic, // CZ
    Germany, // DE
    Djibouti, // DJ
    Denmark, // DK
    Dominica, // DM
    DominicanRepublic, // DO
    Algeria, // DZ
    Ecuador, // EC
    Estonia, // EE
    Egypt, // EG
    WesternSahara, // EH
    Eritrea, // ER
    Spain, // ES
    Ethiopia, // ET
    Finland, // FI
    Fiji, // FJ
    FalklandIslands, // FK
    Micronesia, // FM
    FaroeIslands, // FO
    France, // FR
    MetropolitanFrance, // FX
    Gabon, // GA
    UnitedKingdom, // GB
    Grenada, // GD
    Georgia, // GE
    FrenchGuiana, // GF
    Ghana, // GH
    Gibraltar, // GI
    Greenland, // GL
    Gambia, // GM
    Guinea, // GN
    Guadeloupe, // GP
    EquatorialGuinea, // GQ
    Greece, // GR
    SouthGeorgia, // GS
    Guatemala, // GT
    Guam, // GU
    GuineaBissau, // GW
    Guyana, // GY
    HongKong, // HK
    HeardIslandAndMcDonaldIslands, // HM
    Honduras, // HN
    Croatia, // HR
    Haiti, // HT
    Hungary, // HU
    Indonesia, // ID
    Ireland, // IE
    Israel, // IL
    India, // IN
    BritishIndianOceanTerritory, // IO
    Iraq, // IQ
    Iran, // IR
    Iceland, // IS
    Italy, // IT
    Jamaica, // JM
    Jordan, // JO
    Japan, // JP
    Kenya, // KE
    Kyrgyzstan, // KG
    Cambodia, // KH
    Kiribati, // KI
    Comoros, // KM
    SaintKittsAndNevis, // KN
    NorthKorea, // KP
    SouthKorea, // KR
    Kuwait, // KW
    CaymanIslands, // KY
    Kazakhstan, // KZ
    Laos, // LA
    Lebanon, // LB
    SaintLucia, // LC
    Liechtenstein, // LI
    SriLanka, // LK
    Liberia, // LR
    Lesotho, // LS
    Lithuania, // LT
    Luxembourg, // LU
    Latvia, // LV
    Libya, // LY
    Morocco, // MA
    Monaco, // MC
    Moldova, // MD
    Madagascar, // MG
    MarshallIslands, // MH
    Macedonia, // MK
    Mali, // ML
    Myanmar, // MM
    Mongolia, // MN
    Macao, // MO
    NorthernMarianaIslands, // MP
    Martinique, // MQ
    Mauritania, // MR
    Montserrat, // MS
    Malta, // MT
    Mauritius, // MU
    Maldives, // MV
    Malawi, // MW
    Mexico, // MX
    Malaysia, // MY
    Mozambique, // MZ
    Namibia, // NA
    NewCaledonia, // NC
    Niger, // NE
    NorfolkIsland, // NF
    Nigeria, // NG
    Nicaragua, // NI
    Netherlands, // NL
    Norway, // NO
    Nepal, // NP
    Nauru, // NR
    Niue, // NU
    NewZealand, // NZ
    Oman, // OM
    Panama, // PA
    Peru, // PE
    FrenchPolynesia, // PF
    PapuaNewGuinea, // PG
    Philippines, // PH
    Pakistan, // PK
    Poland, // PL
    SaintPierreAndMiquelon, // PM
    Pitcairn, // PN
    PuertoRico, // PR
    PalestinianTerritory, // PS
    Portugal, // PT
    Palau, // PW
    Paraguay, // PY
    Qatar, // QA
    Reunion, // RE
    Romania, // RO
    Russia, // RU
    Rwanda, // RW
    SaudiArabia, // SA
    SolomonIslands, // SB
    Seychelles, // SC
    Sudan, // SD
    Sweden, // SE
    Singapore, // SG
    SaintHelena, // SH
    Slovenia, // SI
    SvalbardAndJanMayen, // SJ
    Slovakia, // SK
    SierraLeone, // SL
    SanMarino, // SM
    Senegal, // SN
    Somalia, // SO
    Suriname, // SR
    SaoTomeAndPrincipe, // ST
    ElSalvador, // SV
    SyrianArabRepublic, // SY
    Swaziland, // SZ
    TurksAndCaicosIslands, // TC
    Chad, // TD
    FrenchSouthernTerritories, // TF
    Togo, // TG
    Thailand, // TH
    Tajikistan, // TJ
    Tokelau, // TK
    Turkmenistan, // TM
    Tunisia, // TN
    Tonga, // TO
    TimorLeste, // TL
    Turkey, // TR
    TrinidadAndTobago, // TT
    Tuvalu, // TV
    Taiwan, // TW
    Tanzania, // TZ
    Ukraine, // UA
    Uganda, // UG
    USMinorOutlyingIslands, // UM
    UnitedStates, // US
    Uruguay, // UY
    Uzbekistan, // UZ
    Vatican, // VA
    SaintVincentAndTheGrenadines, // VC
    Venezuela, // VE
    BritishVirginIslands, // VG
    USVirginIslands, // VI
    Vietnam, // VN
    Vanuatu, // VU
    WallisAndFutuna, // WF
    Samoa, // WS
    Yemen, // YE
    Mayotte, // YT
    Serbia, // RS
    SouthAfrica, // ZA
    Zambia, // ZM
    Montenegro, // ME
    Zimbabwe, // ZW
    Unknown2, // XX
    SatelliteProvider, // A2
    OtherCountry, // O1
    AlandIslands, // AX
    Guernsey, // GG
    IsleOfMan, // IM
    Jersey, // JE
    SaintBarthelemy, // BL
    SaintMartin, // MF
}